In [ ]:
import exiftool
import glob
import pandas as pd
from IPython.display import display

In [ ]:
ATTRIBUTES = [
    "SourceFile",
    "EXIF:Make",
    "EXIF:DateTimeOriginal",
    "EXIF:ExposureMode",
    "EXIF:ExposureCompensation",
    "MakerNotes:ReleaseMode",
    "MakerNotes:SequenceImageNumber",
    "MakerNotes:SequenceLength",
]

In [ ]:
def show_exif(path_spec):
    files = glob.glob(path_spec)

    with exiftool.ExifToolHelper() as et:
        metadata = et.get_metadata(files)

    filtered_metadata = [{key: item.get(key, None) for key in ATTRIBUTES} for item in metadata]
    df = pd.DataFrame(filtered_metadata)

    df.sort_values(by="SourceFile", inplace=True)
    df.reset_index(drop=True, inplace=True)

    with pd.option_context('display.max_columns', None, 'display.max_rows', None, 'display.max_colwidth', None):
        display(df)

In [43]:
show_exif(r"/Users/anton/Downloads/camera_test_data/sony_zv1_test_hdr/*.ARW")

,SourceFile,EXIF:Make,EXIF:DateTimeOriginal,EXIF:ExposureMode,EXIF:ExposureCompensation,MakerNotes:ReleaseMode,MakerNotes:SequenceImageNumber,MakerNotes:SequenceFileNumber,MakerNotes:SequenceLength
0,/Users/anton/Downloads/camera_test_data/sony_zv1_test_hdr/DSC03566.ARW,SONY,2025:03:29 17:41:39,2,0,5,1,1,9
1,/Users/anton/Downloads/camera_test_data/sony_zv1_test_hdr/DSC03567.ARW,SONY,2025:03:29 17:41:39,2,-1,5,2,2,9
2,/Users/anton/Downloads/camera_test_data/sony_zv1_test_hdr/DSC03568.ARW,SONY,2025:03:29 17:41:39,2,1,5,3,3,9
3,/Users/anton/Downloads/camera_test_data/sony_zv1_test_hdr/DSC03569.ARW,SONY,2025:03:29 17:41:39,2,-2,5,4,4,9
4,/Users/anton/Downloads/camera_test_data/sony_zv1_test_hdr/DSC03570.ARW,SONY,2025:03:29 17:41:39,2,2,5,5,5,9
5,/Users/anton/Downloads/camera_test_data/sony_zv1_test_hdr/DSC03571.ARW,SONY,2025:03:29 17:41:39,2,-3,5,6,6,9
6,/Users/anton/Downloads/camera_test_data/sony_zv1_test_hdr/DSC03572.ARW,SONY,2025:03:29 17:41:39,2,3,5,7,7,9
7,/Users/anton/Downloads/camera_test_data/sony_zv1_test_hdr/DSC03573.ARW,SONY,2025:03:29 17:41:40,2,-4,5,8,8,9
8,/Users/anton/Downloads/camera_test_data/sony_zv1_test_hdr/DSC03574.ARW,SONY,2025:03:29 17:41:40,2,4,5,9,9,9

In [44]:
show_exif(r"/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/*.ARW")

,SourceFile,EXIF:Make,EXIF:DateTimeOriginal,EXIF:ExposureMode,EXIF:ExposureCompensation,MakerNotes:ReleaseMode,MakerNotes:SequenceImageNumber,MakerNotes:SequenceFileNumber,MakerNotes:SequenceLength
0,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02107.ARW,SONY,2025:03:15 17:35:41,0,0.3,0,1,1,1
1,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02108.ARW,SONY,2025:03:15 17:36:56,2,0.3,5,1,1,3
2,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02109.ARW,SONY,2025:03:15 17:36:56,2,-0.7,5,2,2,3
3,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02110.ARW,SONY,2025:03:15 17:36:56,2,1.3,5,3,3,3
4,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02111.ARW,SONY,2025:03:15 17:37:41,2,0.3,5,1,1,3
5,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02112.ARW,SONY,2025:03:15 17:37:41,2,-0.7,5,2,2,3
6,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02113.ARW,SONY,2025:03:15 17:37:42,2,1.3,5,3,3,3
7,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02114.ARW,SONY,2025:03:15 17:55:28,2,0.3,5,1,1,3
8,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02115.ARW,SONY,2025:03:15 17:55:29,2,-0.7,5,2,2,3
9,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02116.ARW,SONY,2025:03:15 17:55:29,2,1.3,5,3,3,3
10,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02117.ARW,SONY,2025:03:15 17:55:30,2,0.3,5,1,1,3
11,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02118.ARW,SONY,2025:03:15 17:55:30,2,-0.7,5,2,2,3
12,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02119.ARW,SONY,2025:03:15 17:55:31,2,0.3,5,1,1,3
13,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02120.ARW,SONY,2025:03:15 17:55:31,2,-0.7,5,2,2,3
14,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02121.ARW,SONY,2025:03:15 17:55:59,2,0.3,5,1,1,3
15,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02122.ARW,SONY,2025:03:15 17:55:59,2,-0.7,5,2,2,3
16,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02123.ARW,SONY,2025:03:15 17:55:59,2,0.3,5,1,1,3
17,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02124.ARW,SONY,2025:03:15 17:55:59,2,-0.7,5,2,2,3
18,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02125.ARW,SONY,2025:03:15 17:55:59,2,1.3,5,3,3,3
19,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02126.ARW,SONY,2025:03:15 17:56:00,2,0.3,5,1,1,3
20,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02127.ARW,SONY,2025:03:15 17:56:00,2,-0.7,5,2,2,3
21,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02128.ARW,SONY,2025:03:15 17:56:00,2,1.3,5,3,3,3
22,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02129.ARW,SONY,2025:03:15 17:56:01,2,0.3,5,1,1,3
23,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02130.ARW,SONY,2025:03:15 17:56:02,2,-0.7,5,2,2,3
24,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02131.ARW,SONY,2025:03:15 17:56:03,2,0.3,5,1,1,3
25,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02132.ARW,SONY,2025:03:15 17:56:03,2,-0.7,5,2,2,3
26,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02133.ARW,SONY,2025:03:15 17:56:03,2,1.3,5,3,3,3
27,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02134.ARW,SONY,2025:03:15 17:56:04,2,0.3,5,1,1,3
28,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02135.ARW,SONY,2025:03:15 17:56:04,2,-0.7,5,2,2,3
29,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02136.ARW,SONY,2025:03:15 17:56:05,2,0.3,5,1,1,3
30,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02137.ARW,SONY,2025:03:15 17:56:05,2,-0.7,5,2,2,3
31,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02138.ARW,SONY,2025:03:15 17:56:06,2,0.3,5,1,1,3
32,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02139.ARW,SONY,2025:03:15 17:56:06,2,-0.7,5,2,2,3
33,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02140.ARW,SONY,2025:03:15 17:56:07,2,1.3,5,3,3,3
34,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02141.ARW,SONY,2025:03:15 17:56:11,2,0.3,5,1,1,3
35,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02142.ARW,SONY,2025:03:15 17:56:11,2,-0.7,5,2,2,3
36,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02143.ARW,SONY,2025:03:15 17:56:11,2,1.3,5,3,3,3
37,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02144.ARW,SONY,2025:03:15 17:56:17,2,0.3,5,1,1,3
38,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02145.ARW,SONY,2025:03:15 17:56:17,2,-0.7,5,2,2,3
39,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02146.ARW,SONY,2025:03:15 17:56:17,2,1.3,5,3,3,3
40,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02147.ARW,SONY,2025:03:15 17:56:18,2,0.3,5,1,1,3
41,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02148.ARW,SONY,2025:03:15 17:56:18,2,-0.7,5,2,2,3
42,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02149.ARW,SONY,2025:03:15 17:56:18,2,1.3,5,3,3,3
43,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02150.ARW,SONY,2025:03:15 17:59:05,2,0.3,5,1,1,3
44,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02151.ARW,SONY,2025:03:15 17:59:05,2,-0.7,5,2,2,3
45,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02152.ARW,SONY,2025:03:15 17:59:05,2,1.3,5,3,3,3
46,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02153.ARW,SONY,2025:03:15 17:59:20,2,0.3,5,1,1,3
47,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02154.ARW,SONY,2025:03:15 17:59:20,2,-0.7,5,2,2,3
48,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02155.ARW,SONY,2025:03:15 17:59:20,2,1.3,5,3,3,3
49,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02156.ARW,SONY,2025:03:15 17:59:29,2,0.3,5,1,1,3
50,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02157.ARW,SONY,2025:03:15 17:59:29,2,-0.7,5,2,2,3
51,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02158.ARW,SONY,2025:03:15 17:59:30,2,1.3,5,3,3,3
52,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02159.ARW,SONY,2025:03:15 17:59:45,0,0.3,0,1,1,1
53,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02160.ARW,SONY,2025:03:15 17:59:47,0,0.3,0,1,1,1
54,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02161.ARW,SONY,2025:03:15 17:59:49,0,0.3,0,1,1,1
55,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02162.ARW,SONY,2025:03:15 18:00:14,0,0.3,0,1,1,1
56,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02163.ARW,SONY,2025:03:15 18:00:54,0,0.3,0,1,1,1
57,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02164.ARW,SONY,2025:03:15 18:01:19,0,0.3,0,1,1,1
58,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02165.ARW,SONY,2025:03:15 18:02:19,0,0.3,0,1,1,1
59,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02166.ARW,SONY,2025:03:15 18:02:21,0,0.3,0,1,1,1
60,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02167.ARW,SONY,2025:03:15 18:02:22,0,0.3,0,1,1,1
61,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02168.ARW,SONY,2025:03:15 18:02:23,0,0.3,0,1,1,1
62,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02169.ARW,SONY,2025:03:15 18:02:24,0,0.3,0,1,1,1
63,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02170.ARW,SONY,2025:03:15 18:02:25,0,0.3,0,1,1,1
64,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02171.ARW,SONY,2025:03:15 18:02:26,0,0.3,0,1,1,1
65,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02172.ARW,SONY,2025:03:15 18:02:27,0,0.3,0,1,1,1
66,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02173.ARW,SONY,2025:03:15 18:02:29,0,0.3,0,1,1,1
67,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02174.ARW,SONY,2025:03:15 18:02:30,0,0.3,0,1,1,1
68,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02175.ARW,SONY,2025:03:15 18:02:31,0,0.3,0,1,1,1
69,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02176.ARW,SONY,2025:03:15 18:02:32,0,0.3,0,1,1,1
70,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02177.ARW,SONY,2025:03:15 18:03:41,0,0.3,0,1,1,1
71,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02178.ARW,SONY,2025:03:15 18:03:42,0,0.3,0,1,1,1
72,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02179.ARW,SONY,2025:03:15 18:03:43,0,0.3,0,1,1,1
73,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02180.ARW,SONY,2025:03:15 18:03:44,0,0.3,0,1,1,1
74,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02181.ARW,SONY,2025:03:15 18:03:46,0,0.3,0,1,1,1
75,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02182.ARW,SONY,2025:03:15 18:04:04,0,0.3,0,1,1,1
76,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02183.ARW,SONY,2025:03:15 18:05:00,0,0.3,0,1,1,1
77,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02184.ARW,SONY,2025:03:15 18:07:25,0,0.3,0,1,1,1
78,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02185.ARW,SONY,2025:03:15 18:07:26,0,0.3,0,1,1,1
79,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02186.ARW,SONY,2025:03:15 18:07:31,0,0.3,0,1,1,1
80,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02187.ARW,SONY,2025:03:15 18:07:36,0,0.3,0,1,1,1
81,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02188.ARW,SONY,2025:03:15 18:07:40,0,0.3,0,1,1,1
82,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02189.ARW,SONY,2025:03:15 18:07:43,0,0.3,0,1,1,1
83,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02190.ARW,SONY,2025:03:15 18:08:04,0,0.3,0,1,1,1
84,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02191.ARW,SONY,2025:03:15 18:08:08,0,0.3,0,1,1,1
85,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02192.ARW,SONY,2025:03:15 18:08:10,0,0.3,0,1,1,1
86,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02193.ARW,SONY,2025:03:15 18:08:12,0,0.3,0,1,1,1
87,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02194.ARW,SONY,2025:03:15 18:08:22,0,0.3,0,1,1,1
88,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02195.ARW,SONY,2025:03:15 18:08:25,0,0.3,0,1,1,1
89,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02196.ARW,SONY,2025:03:15 18:08:28,0,0.3,0,1,1,1
90,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02197.ARW,SONY,2025:03:15 18:09:25,0,0.3,0,1,1,1
91,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02198.ARW,SONY,2025:03:15 18:09:26,0,0.3,0,1,1,1
92,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02199.ARW,SONY,2025:03:15 18:09:28,0,0.3,0,1,1,1
93,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02200.ARW,SONY,2025:03:15 18:09:29,0,0.3,0,1,1,1
94,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02201.ARW,SONY,2025:03:15 18:09:38,0,0.3,0,1,1,1
95,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02202.ARW,SONY,2025:03:15 18:09:39,0,0.3,0,1,1,1
96,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02203.ARW,SONY,2025:03:15 18:09:42,0,0.3,0,1,1,1
97,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02204.ARW,SONY,2025:03:15 18:09:43,0,0.3,0,1,1,1
98,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02205.ARW,SONY,2025:03:15 18:09:45,0,0.3,0,1,1,1
99,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02206.ARW,SONY,2025:03:15 18:09:46,0,0.3,0,1,1,1
100,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02207.ARW,SONY,2025:03:15 18:09:54,2,0.3,5,1,1,3
101,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02208.ARW,SONY,2025:03:15 18:09:54,2,-0.7,5,2,2,3
102,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02209.ARW,SONY,2025:03:15 18:09:54,2,1.3,5,3,3,3
103,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02210.ARW,SONY,2025:03:15 18:10:47,0,0.3,0,1,1,1
104,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02211.ARW,SONY,2025:03:15 18:26:47,2,0.3,5,1,1,3
105,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02212.ARW,SONY,2025:03:15 18:26:47,2,-0.7,5,2,2,3
106,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02213.ARW,SONY,2025:03:15 18:26:47,2,1.3,5,3,3,3
107,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02214.ARW,SONY,2025:03:15 18:26:56,2,0.3,5,1,1,3
108,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02215.ARW,SONY,2025:03:15 18:26:56,2,-0.7,5,2,2,3
109,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02216.ARW,SONY,2025:03:15 18:26:56,2,1.3,5,3,3,3
110,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02217.ARW,SONY,2025:03:15 18:27:06,2,0.3,5,1,1,3
111,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02218.ARW,SONY,2025:03:15 18:27:06,2,-0.7,5,2,2,3
112,/Users/anton/Downloads/camera_test_data/sony_a7c_mixed/DSC02219.ARW,SONY,2025:03:15 18:27:06,2,1.3,5,3,3,3

In [45]:
show_exif(r"/Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/*.ARW")

                                                                    SourceFile  \
0     /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05441.ARW
1     /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05442.ARW
2     /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05443.ARW
3     /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05444.ARW
4     /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05445.ARW
5     /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05446.ARW
6     /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05447.ARW
7     /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05448.ARW
8     /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05449.ARW
9     /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05450.ARW
10    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05451.ARW
11    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05452.ARW
12    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05453.ARW
13    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05454.ARW
14    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05455.ARW
15    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05456.ARW
16    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05457.ARW
17    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05458.ARW
18    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05459.ARW
19    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05460.ARW
20    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05461.ARW
21    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05462.ARW
22    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05463.ARW
23    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05464.ARW
24    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05465.ARW
25    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05466.ARW
26    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05467.ARW
27    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05468.ARW
28    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05469.ARW
29    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05470.ARW
30    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05471.ARW
31    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05472.ARW
32    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05473.ARW
33    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05474.ARW
34    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05475.ARW
35    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05476.ARW
36    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05477.ARW
37    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05478.ARW
38    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05479.ARW
39    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05480.ARW
40    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05481.ARW
41    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05482.ARW
42    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05483.ARW
43    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05484.ARW
44    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05485.ARW
45    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05486.ARW
46    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05487.ARW
47    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05488.ARW
48    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05489.ARW
49    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05490.ARW
50    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05491.ARW
51    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05492.ARW
52    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05493.ARW
53    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05494.ARW
54    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05495.ARW
55    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05496.ARW
56    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05497.ARW
57    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05498.ARW
58    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05499.ARW
59    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05500.ARW
60    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05501.ARW
61    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05502.ARW
62    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05503.ARW
63    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05504.ARW
64    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05505.ARW
65    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05506.ARW
66    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05507.ARW
67    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05508.ARW
68    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05509.ARW
69    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05510.ARW
70    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05511.ARW
71    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05512.ARW
72    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05513.ARW
73    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05514.ARW
74    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05515.ARW
75    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05516.ARW
76    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05517.ARW
77    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05518.ARW
78    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05519.ARW
79    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05520.ARW
80    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05521.ARW
81    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05522.ARW
82    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05523.ARW
83    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05524.ARW
84    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05525.ARW
85    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05526.ARW
86    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05527.ARW
87    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05528.ARW
88    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05529.ARW
89    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05530.ARW
90    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05531.ARW
91    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05532.ARW
92    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05533.ARW
93    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05534.ARW
94    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05535.ARW
95    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05536.ARW
96    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05537.ARW
97    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05538.ARW
98    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05539.ARW
99    /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05540.ARW
100   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05541.ARW
101   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05542.ARW
102   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05543.ARW
103   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05544.ARW
104   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05545.ARW
105   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05546.ARW
106   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05547.ARW
107   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05548.ARW
108   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05549.ARW
109   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05550.ARW
110   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05551.ARW
111   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05552.ARW
112   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05553.ARW
113   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05554.ARW
114   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05555.ARW
115   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05556.ARW
116   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05557.ARW
117   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05558.ARW
118   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05559.ARW
119   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05560.ARW
120   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05561.ARW
121   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05562.ARW
122   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05563.ARW
123   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05564.ARW
124   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05565.ARW
125   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05566.ARW
126   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05567.ARW
127   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05568.ARW
128   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05569.ARW
129   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05570.ARW
130   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05571.ARW
131   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05572.ARW
132   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05573.ARW
133   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05574.ARW
134   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05575.ARW
135   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05576.ARW
136   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05577.ARW
137   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05578.ARW
138   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05579.ARW
139   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05580.ARW
140   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05581.ARW
141   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05582.ARW
142   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05583.ARW
143   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05584.ARW
144   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05585.ARW
145   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05586.ARW
146   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05587.ARW
147   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05588.ARW
148   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05589.ARW
149   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05590.ARW
150   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05591.ARW
151   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05592.ARW
152   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05593.ARW
153   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05594.ARW
154   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05595.ARW
155   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05596.ARW
156   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05597.ARW
157   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05598.ARW
158   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05599.ARW
159   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05600.ARW
160   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05601.ARW
161   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05602.ARW
162   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05603.ARW
163   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05604.ARW
164   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05605.ARW
165   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05606.ARW
166   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05607.ARW
167   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05608.ARW
168   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05609.ARW
169   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05610.ARW
170   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05611.ARW
171   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05612.ARW
172   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05613.ARW
173   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05614.ARW
174   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05615.ARW
175   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05616.ARW
176   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05617.ARW
177   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05618.ARW
178   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05619.ARW
179   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05620.ARW
180   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05621.ARW
181   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05622.ARW
182   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05623.ARW
183   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05624.ARW
184   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05625.ARW
185   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05626.ARW
186   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05627.ARW
187   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05628.ARW
188   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05629.ARW
189   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05630.ARW
190   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05631.ARW
191   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05632.ARW
192   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05633.ARW
193   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05634.ARW
194   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05635.ARW
195   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05636.ARW
196   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05637.ARW
197   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05638.ARW
198   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05639.ARW
199   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05640.ARW
200   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05641.ARW
201   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05642.ARW
202   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05643.ARW
203   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05644.ARW
204   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05645.ARW
205   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05646.ARW
206   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05647.ARW
207   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05648.ARW
208   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05649.ARW
209   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05650.ARW
210   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05651.ARW
211   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05652.ARW
212   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05653.ARW
213   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05654.ARW
214   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05655.ARW
215   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05656.ARW
216   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05657.ARW
217   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05658.ARW
218   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05659.ARW
219   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05660.ARW
220   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05661.ARW
221   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05662.ARW
222   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05663.ARW
223   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05664.ARW
224   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05665.ARW
225   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05666.ARW
226   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05667.ARW
227   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05668.ARW
228   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05669.ARW
229   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05670.ARW
230   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05671.ARW
231   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05672.ARW
232   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05673.ARW
233   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05674.ARW
234   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05675.ARW
235   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05676.ARW
236   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05677.ARW
237   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05678.ARW
238   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05679.ARW
239   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05680.ARW
240   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05681.ARW
241   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05682.ARW
242   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05683.ARW
243   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05684.ARW
244   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05685.ARW
245   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05686.ARW
246   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05687.ARW
247   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05688.ARW
248   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05689.ARW
249   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05690.ARW
250   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05691.ARW
251   /Users/anton/Downloads/camera_test_data/sony_rx100vii_mixed/DSC05692.ARW

In [ ]:
from pathlib import Path

# Specify the directory
directory = Path("/Users/anton/Downloads/camera_test_data/sony_zv1_test_hdr")

# List all files with .ARW extension
arw_files = list(directory.glob("*.ARW"))

# Print the file names
for file in arw_files:
    print(file.name)

['DSC05969.ARW',
 'DSC07818.ARW',
 'DSC07830.ARW',
 'DSC06290.ARW',
 'DSC05941.ARW',
 'DSC05799.ARW',
 'DSC05955.ARW',
 'DSC06284.ARW',
 'DSC07824.ARW',
 'DSC06509.ARW',
 'DSC07617.ARW',
 'DSC07171.ARW',
 'DSC05766.ARW',
 'DSC05772.ARW',
 'DSC07165.ARW',
 'DSC07603.ARW',
 'DSC06535.ARW',
 'DSC05982.ARW',
 'DSC06253.ARW',
 'DSC07159.ARW',
 'DSC06247.ARW',
 'DSC05996.ARW',
 'DSC06521.ARW',
 'DSC06910.ARW',
 'DSC06904.ARW',
 'DSC06092.ARW',
 'DSC06938.ARW',
 'DSC07398.ARW',
 'DSC06086.ARW',
 'DSC05564.ARW',
 'DSC07373.ARW',
 'DSC07415.ARW',
 'DSC07401.ARW',
 'DSC06079.ARW',
 'DSC07367.ARW',
 'DSC05570.ARW',
 'DSC06051.ARW',
 'DSC05558.ARW',
 'DSC07429.ARW',
 'DSC06737.ARW',
 'DSC06723.ARW',
 'DSC06045.ARW',
 'DSC06864.ARW',
 'DSC06870.ARW',
 'DSC06680.ARW',
 'DSC06694.ARW',
 'DSC07207.ARW',
 'DSC06119.ARW',
 'DSC07561.ARW',
 'DSC07575.ARW',
 'DSC07213.ARW',
 'DSC06125.ARW',
 'DSC06643.ARW',
 'DSC06657.ARW',
 'DSC07549.ARW',
 'DSC06131.ARW',
 'DSC05809.ARW',
 'DSC06482.ARW',
 'DSC05835.ARW',
 'DSC05821.ARW',
 'DSC06496.ARW',
 'DSC07788.ARW',
 'DSC07763.ARW',
 'DSC07005.ARW',
 'DSC05612.ARW',
 'DSC05606.ARW',
 'DSC07011.ARW',
 'DSC07777.ARW',
 'DSC06469.ARW',
 'DSC06441.ARW',
 'DSC06327.ARW',
 'DSC07039.ARW',
 'DSC06333.ARW',
 'DSC06455.ARW',
 'DSC06332.ARW',
 'DSC06454.ARW',
 'DSC06440.ARW',
 'DSC07038.ARW',
 'DSC06326.ARW',
 'DSC07010.ARW',
 'DSC05607.ARW',
 'DSC06468.ARW',
 'DSC07776.ARW',
 'DSC07762.ARW',
 'DSC05613.ARW',
 'DSC07004.ARW',
 'DSC05820.ARW',
 'DSC07789.ARW',
 'DSC06497.ARW',
 'DSC06483.ARW',
 'DSC05834.ARW',
 'DSC05808.ARW',
 'DSC07548.ARW',
 'DSC06656.ARW',
 'DSC06130.ARW',
 'DSC06124.ARW',
 'DSC06642.ARW',
 'DSC07574.ARW',
 'DSC07212.ARW',
 'DSC06118.ARW',
 'DSC07206.ARW',
 'DSC07560.ARW',
 'DSC06695.ARW',
 'DSC06681.ARW',
 'DSC06859.ARW',
 'DSC06871.ARW',
 'DSC06865.ARW',
 'DSC06722.ARW',
 'DSC06044.ARW',
 'DSC05559.ARW',
 'DSC06050.ARW',
 'DSC06736.ARW',
 'DSC07428.ARW',
 'DSC07400.ARW',
 'DSC05571.ARW',
 'DSC07366.ARW',
 'DSC06078.ARW',
 'DSC07372.ARW',
 'DSC05565.ARW',
 'DSC07414.ARW',
 'DSC06939.ARW',
 'DSC06087.ARW',
 'DSC07399.ARW',
 'DSC06093.ARW',
 'DSC06905.ARW',
 'DSC06911.ARW',
 'DSC05997.ARW',
 'DSC06246.ARW',
 'DSC07158.ARW',
 'DSC06520.ARW',
 'DSC06534.ARW',
 'DSC06252.ARW',
 'DSC05983.ARW',
 'DSC07164.ARW',
 'DSC05773.ARW',
 'DSC07602.ARW',
 'DSC07616.ARW',
 'DSC06508.ARW',
 'DSC05767.ARW',
 'DSC07170.ARW',
 'DSC06285.ARW',
 'DSC05954.ARW',
 'DSC07825.ARW',
 'DSC07831.ARW',
 'DSC05798.ARW',
 'DSC05940.ARW',
 'DSC06291.ARW',
 'DSC05968.ARW',
 'DSC07819.ARW',
 'DSC07827.ARW',
 'DSC05956.ARW',
 'DSC06287.ARW',
 'DSC07199.ARW',
 'DSC06293.ARW',
 'DSC05942.ARW',
 'DSC07833.ARW',
 'DSC07600.ARW',
 'DSC05771.ARW',
 'DSC07166.ARW',
 'DSC06278.ARW',
 'DSC07172.ARW',
 'DSC05765.ARW',
 'DSC07614.ARW',
 'DSC06522.ARW',
 'DSC06244.ARW',
 'DSC05995.ARW',
 'DSC05759.ARW',
 'DSC05981.ARW',
 'DSC06250.ARW',
 'DSC06536.ARW',
 'DSC07628.ARW',
 'DSC06907.ARW',
 'DSC06913.ARW',
 'DSC06085.ARW',
 'DSC05598.ARW',
 'DSC06091.ARW',
 'DSC07364.ARW',
 'DSC05573.ARW',
 'DSC07402.ARW',
 'DSC07416.ARW',
 'DSC06708.ARW',
 'DSC05567.ARW',
 'DSC07370.ARW',
 'DSC06046.ARW',
 'DSC07358.ARW',
 'DSC06720.ARW',
 'DSC06734.ARW',
 'DSC06052.ARW',
 'DSC06873.ARW',
 'DSC06867.ARW',
 'DSC07589.ARW',
 'DSC06697.ARW',
 'DSC06683.ARW',
 'DSC07210.ARW',
 'DSC06668.ARW',
 'DSC07576.ARW',
 'DSC07562.ARW',
 'DSC07204.ARW',
 'DSC06132.ARW',
 'DSC06654.ARW',
 'DSC06640.ARW',
 'DSC06898.ARW',
 'DSC07238.ARW',
 'DSC06126.ARW',
 'DSC06495.ARW',
 'DSC05822.ARW',
 'DSC05836.ARW',
 'DSC06481.ARW',
 'DSC07774.ARW',
 'DSC05605.ARW',
 'DSC07012.ARW',
 'DSC06318.ARW',
 'DSC07006.ARW',
 'DSC05611.ARW',
 'DSC07760.ARW',
 'DSC07748.ARW',
 'DSC06456.ARW',
 'DSC06330.ARW',
 'DSC05639.ARW',
 'DSC06324.ARW',
 'DSC06442.ARW',
 'DSC06325.ARW',
 'DSC06443.ARW',
 'DSC06457.ARW',
 'DSC07749.ARW',
 'DSC05638.ARW',
 'DSC06331.ARW',
 'DSC05610.ARW',
 'DSC07007.ARW',
 'DSC06319.ARW',
 'DSC07761.ARW',
 'DSC07775.ARW',
 'DSC07013.ARW',
 'DSC05604.ARW',
 'DSC05837.ARW',
 'DSC06480.ARW',
 'DSC06494.ARW',
 'DSC05823.ARW',
 'DSC06899.ARW',
 'DSC06641.ARW',
 'DSC06127.ARW',
 'DSC07239.ARW',
 'DSC06133.ARW',
 'DSC06655.ARW',
 'DSC07563.ARW',
 'DSC07205.ARW',
 'DSC07211.ARW',
 'DSC07577.ARW',
 'DSC06669.ARW',
 'DSC06682.ARW',
 'DSC06696.ARW',
 'DSC07588.ARW',
 'DSC06866.ARW',
 'DSC06872.ARW',
 'DSC06735.ARW',
 'DSC06053.ARW',
 'DSC07359.ARW',
 'DSC06047.ARW',
 'DSC06721.ARW',
 'DSC06709.ARW',
 'DSC07417.ARW',
 'DSC07371.ARW',
 'DSC05566.ARW',
 'DSC05572.ARW',
 'DSC07365.ARW',
 'DSC07403.ARW',
 'DSC06090.ARW',
 'DSC05599.ARW',
 'DSC06084.ARW',
 'DSC06912.ARW',
 'DSC06906.ARW',
 'DSC06251.ARW',
 'DSC05980.ARW',
 'DSC05758.ARW',
 'DSC07629.ARW',
 'DSC06537.ARW',
 'DSC06523.ARW',
 'DSC05994.ARW',
 'DSC06245.ARW',
 'DSC05764.ARW',
 'DSC07173.ARW',
 'DSC07615.ARW',
 'DSC07601.ARW',
 'DSC06279.ARW',
 'DSC07167.ARW',
 'DSC05770.ARW',
 'DSC05943.ARW',
 'DSC06292.ARW',
 'DSC07832.ARW',
 'DSC07826.ARW',
 'DSC07198.ARW',
 'DSC06286.ARW',
 'DSC05957.ARW',
 'DSC05953.ARW',
 'DSC06282.ARW',
 'DSC07822.ARW',
 'DSC07836.ARW',
 'DSC06296.ARW',
 'DSC07188.ARW',
 'DSC05947.ARW',
 'DSC06241.ARW',
 'DSC05748.ARW',
 'DSC05990.ARW',
 'DSC06527.ARW',
 'DSC07639.ARW',
 'DSC06533.ARW',
 'DSC05984.ARW',
 'DSC06255.ARW',
 'DSC05774.ARW',
 'DSC07163.ARW',
 'DSC07605.ARW',
 'DSC07611.ARW',
 'DSC07177.ARW',
 'DSC06269.ARW',
 'DSC05760.ARW',
 'DSC06080.ARW',
 'DSC05589.ARW',
 'DSC06094.ARW',
 'DSC06902.ARW',
 'DSC06916.ARW',
 'DSC06725.ARW',
 'DSC06043.ARW',
 'DSC06057.ARW',
 'DSC07349.ARW',
 'DSC06731.ARW',
 'DSC07407.ARW',
 'DSC06719.ARW',
 'DSC07361.ARW',
 'DSC05576.ARW',
 'DSC05562.ARW',
 'DSC07375.ARW',
 'DSC07413.ARW',
 'DSC06692.ARW',
 'DSC07598.ARW',
 'DSC06686.ARW',
 'DSC06876.ARW',
 'DSC06862.ARW',
 'DSC06651.ARW',
 'DSC06889.ARW',
 'DSC07229.ARW',
 'DSC06137.ARW',
 'DSC06123.ARW',
 'DSC06645.ARW',
 'DSC07573.ARW',
 'DSC07215.ARW',
 'DSC07201.ARW',
 'DSC06679.ARW',
 'DSC07567.ARW',
 'DSC05827.ARW',
 'DSC06490.ARW',
 '.DS_Store',
 'DSC06484.ARW',
 'DSC05833.ARW',
 'DSC06335.ARW',
 'DSC06453.ARW',
 'DSC07759.ARW',
 'DSC06447.ARW',
 'DSC05628.ARW',
 'DSC06321.ARW',
 'DSC05600.ARW',
 'DSC06309.ARW',
 'DSC07017.ARW',
 'DSC07771.ARW',
 'DSC07765.ARW',
 'DSC07003.ARW',
 'DSC05614.ARW',
 'DSC07764.ARW',
 'DSC05615.ARW',
 'DSC07002.ARW',
 'DSC07016.ARW',
 'DSC06308.ARW',
 'DSC05601.ARW',
 'DSC07770.ARW',
 'DSC06446.ARW',
 'DSC07758.ARW',
 'DSC06320.ARW',
 'DSC05629.ARW',
 'DSC06334.ARW',
 'DSC06452.ARW',
 'DSC06485.ARW',
 'DSC05832.ARW',
 'DSC05826.ARW',
 'DSC06491.ARW',
 'DSC07200.ARW',
 'DSC07566.ARW',
 'DSC06678.ARW',
 'DSC07572.ARW',
 'DSC07214.ARW',
 'DSC06122.ARW',
 'DSC06644.ARW',
 'DSC06888.ARW',
 'DSC06650.ARW',
 'DSC06136.ARW',
 'DSC07228.ARW',
 'DSC06863.ARW',
 'DSC06877.ARW',
 'DSC06687.ARW',
 'DSC07599.ARW',
 'DSC06693.ARW',
 'DSC07374.ARW',
 'DSC05563.ARW',
 'DSC07412.ARW',
 'DSC06718.ARW',
 'DSC07406.ARW',
 'DSC05577.ARW',
 'DSC07360.ARW',
 'DSC07348.ARW',
 'DSC06056.ARW',
 'DSC06730.ARW',
 'DSC06724.ARW',
 'DSC06042.ARW',
 'DSC06917.ARW',
 'DSC06903.ARW',
 'DSC06095.ARW',
 'DSC05588.ARW',
 'DSC06081.ARW',
 'DSC07610.ARW',
 'DSC05761.ARW',
 'DSC06268.ARW',
 'DSC07176.ARW',
 'DSC07162.ARW',
 'DSC05775.ARW',
 'DSC07604.ARW',
 'DSC06532.ARW',
 'DSC06254.ARW',
 'DSC05985.ARW',
 'DSC05991.ARW',
 'DSC05749.ARW',
 'DSC06240.ARW',
 'DSC07638.ARW',
 'DSC06526.ARW',
 'DSC07837.ARW',
 'DSC05946.ARW',
 'DSC07189.ARW',
 'DSC06297.ARW',
 'DSC06283.ARW',
 'DSC05952.ARW',
 'DSC07823.ARW',
 'DSC06295.ARW',
 'DSC05944.ARW',
 'DSC07835.ARW',
 'DSC07821.ARW',
 'DSC05950.ARW',
 'DSC05788.ARW',
 'DSC06281.ARW',
 'DSC05978.ARW',
 'DSC07809.ARW',
 'DSC05987.ARW',
 'DSC07148.ARW',
 'DSC06256.ARW',
 'DSC06530.ARW',
 'DSC06524.ARW',
 'DSC06242.ARW',
 'DSC05993.ARW',
 'DSC07174.ARW',
 'DSC05763.ARW',
 'DSC07612.ARW',
 'DSC06518.ARW',
 'DSC07606.ARW',
 'DSC05777.ARW',
 'DSC07160.ARW',
 'DSC06929.ARW',
 'DSC07389.ARW',
 'DSC06097.ARW',
 'DSC06083.ARW',
 'DSC06915.ARW',
 'DSC06901.ARW',
 'DSC06732.ARW',
 'DSC06054.ARW',
 'DSC05549.ARW',
 'DSC06040.ARW',
 'DSC07438.ARW',
 'DSC06726.ARW',
 'DSC07410.ARW',
 'DSC05561.ARW',
 'DSC06068.ARW',
 'DSC07376.ARW',
 'DSC07362.ARW',
 'DSC05575.ARW',
 'DSC07404.ARW',
 'DSC06685.ARW',
 'DSC06849.ARW',
 'DSC06691.ARW',
 'DSC06861.ARW',
 'DSC06875.ARW',
 'DSC06646.ARW',
 'DSC07558.ARW',
 'DSC06120.ARW',
 'DSC06134.ARW',
 'DSC06652.ARW',
 'DSC07564.ARW',
 'DSC07202.ARW',
 'DSC07216.ARW',
 'DSC06108.ARW',
 'DSC07570.ARW',
 'DSC05830.ARW',
 'DSC06487.ARW',
 'DSC07799.ARW',
 'DSC06493.ARW',
 'DSC05824.ARW',
 'DSC05818.ARW',
 'DSC06322.ARW',
 'DSC06444.ARW',
 'DSC06450.ARW',
 'DSC06336.ARW',
 'DSC07028.ARW',
 'DSC07000.ARW',
 'DSC05617.ARW',
 'DSC07766.ARW',
 'DSC06478.ARW',
 'DSC07772.ARW',
 'DSC05603.ARW',
 'DSC07014.ARW',
 'DSC07773.ARW',
 'DSC07015.ARW',
 'DSC05602.ARW',
 'DSC05616.ARW',
 'DSC07001.ARW',
 'DSC06479.ARW',
 'DSC07767.ARW',
 'DSC06451.ARW',
 'DSC07029.ARW',
 'DSC06337.ARW',
 'DSC06323.ARW',
 'DSC06445.ARW',
 'DSC05819.ARW',
 'DSC06492.ARW',
 'DSC05825.ARW',
 'DSC05831.ARW',
 'DSC07798.ARW',
 'DSC06486.ARW',
 'DSC06109.ARW',
 'DSC07217.ARW',
 'DSC07571.ARW',
 'DSC07565.ARW',
 'DSC07203.ARW',
 'DSC06135.ARW',
 'DSC06653.ARW',
 'DSC07559.ARW',
 'DSC06647.ARW',
 'DSC06121.ARW',
 'DSC06874.ARW',
 'DSC06860.ARW',
 'DSC06690.ARW',
 'DSC06848.ARW',
 'DSC06684.ARW',
 'DSC05574.ARW',
 'DSC07363.ARW',
 'DSC07405.ARW',
 'DSC07411.ARW',
 'DSC07377.ARW',
 'DSC06069.ARW',
 'DSC05560.ARW',
 'DSC06041.ARW',
 'DSC05548.ARW',
 'DSC06727.ARW',
 'DSC07439.ARW',
 'DSC06733.ARW',
 'DSC06055.ARW',
 'DSC06900.ARW',
 'DSC06914.ARW',
 'DSC06082.ARW',
 'DSC06928.ARW',
 'DSC06096.ARW',
 'DSC07388.ARW',
 'DSC07607.ARW',
 'DSC06519.ARW',
 'DSC07161.ARW',
 'DSC05776.ARW',
 'DSC05762.ARW',
 'DSC07175.ARW',
 'DSC07613.ARW',
 'DSC06525.ARW',
 'DSC05992.ARW',
 'DSC06243.ARW',
 'DSC06257.ARW',
 'DSC07149.ARW',
 'DSC05986.ARW',
 'DSC06531.ARW',
 'DSC05979.ARW',
 'DSC07808.ARW',
 'DSC07820.ARW',
 'DSC06280.ARW',
 'DSC05789.ARW',
 'DSC05951.ARW',
 'DSC05945.ARW',
 'DSC06294.ARW',
 'DSC07834.ARW',
 'DSC05922.ARW',
 'DSC07853.ARW',
 'DSC06595.ARW',
 'DSC07847.ARW',
 'DSC06581.ARW',
 'DSC05936.ARW',
 'DSC05705.ARW',
 'DSC07112.ARW',
 'DSC07674.ARW',
 'DSC07660.ARW',
 'DSC07106.ARW',
 'DSC06218.ARW',
 'DSC05711.ARW',
 'DSC06230.ARW',
 'DSC05739.ARW',
 'DSC07890.ARW',
 'DSC06556.ARW',
 'DSC07648.ARW',
 'DSC07884.ARW',
 'DSC06542.ARW',
 'DSC06224.ARW',
 'DSC06973.ARW',
 'DSC06967.ARW',
 'DSC06797.ARW',
 'DSC07489.ARW',
 'DSC06783.ARW',
 'DSC07476.ARW',
 'DSC06768.ARW',
 'DSC07310.ARW',
 'DSC05507.ARW',
 'DSC05513.ARW',
 'DSC07304.ARW',
 'DSC07462.ARW',
 'DSC06754.ARW',
 'DSC06032.ARW',
 'DSC06026.ARW',
 'DSC07338.ARW',
 'DSC06998.ARW',
 'DSC06740.ARW',
 'DSC06807.ARW',
 'DSC06813.ARW',
 'DSC06185.ARW',
 'DSC05498.ARW',
 'DSC06191.ARW',
 'DSC07502.ARW',
 'DSC07264.ARW',
 'DSC05473.ARW',
 'DSC05467.ARW',
 'DSC07270.ARW',
 'DSC06608.ARW',
 'DSC07516.ARW',
 'DSC06620.ARW',
 'DSC07258.ARW',
 'DSC06146.ARW',
 'DSC06152.ARW',
 'DSC06634.ARW',
 'DSC05856.ARW',
 'DSC07099.ARW',
 'DSC06387.ARW',
 'DSC06393.ARW',
 'DSC05842.ARW',
 'DSC05671.ARW',
 'DSC06378.ARW',
 'DSC07066.ARW',
 'DSC07700.ARW',
 'DSC07714.ARW',
 'DSC07072.ARW',
 'DSC05665.ARW',
 'DSC06344.ARW',
 'DSC05895.ARW',
 'DSC06422.ARW',
 'DSC06436.ARW',
 'DSC05881.ARW',
 'DSC05659.ARW',
 'DSC06350.ARW',
 'DSC06437.ARW',
 'DSC06351.ARW',
 'DSC05658.ARW',
 'DSC05880.ARW',
 'DSC05894.ARW',
 'DSC06345.ARW',
 'DSC06423.ARW',
 'DSC07715.ARW',
 'DSC05664.ARW',
 'DSC07073.ARW',
 'DSC07067.ARW',
 'DSC06379.ARW',
 'DSC05670.ARW',
 'DSC07701.ARW',
 'DSC05843.ARW',
 'DSC06392.ARW',
 'DSC06386.ARW',
 'DSC07098.ARW',
 'DSC05857.ARW',
 'DSC06153.ARW',
 'DSC06635.ARW',
 'DSC06621.ARW',
 'DSC06147.ARW',
 'DSC07259.ARW',
 'DSC07271.ARW',
 'DSC05466.ARW',
 'DSC07517.ARW',
 'DSC06609.ARW',
 'DSC07503.ARW',
 'DSC05472.ARW',
 'DSC07265.ARW',
 'DSC06190.ARW',
 'DSC05499.ARW',
 'DSC06184.ARW',
 'DSC06812.ARW',
 'DSC06806.ARW',
 'DSC07339.ARW',
 'DSC06027.ARW',
 'DSC06741.ARW',
 'DSC06999.ARW',
 'DSC06755.ARW',
 'DSC06033.ARW',
 'DSC07305.ARW',
 'DSC05512.ARW',
 'DSC07463.ARW',
 'DSC06769.ARW',
 'DSC07477.ARW',
 'DSC05506.ARW',
 'DSC07311.ARW',
 'DSC06782.ARW',
 'DSC07488.ARW',
 'DSC06796.ARW',
 'DSC06966.ARW',
 'DSC06972.ARW',
 'DSC06543.ARW',
 'DSC07885.ARW',
 'DSC06225.ARW',
 'DSC05738.ARW',
 'DSC06231.ARW',
 'DSC07649.ARW',
 'DSC06557.ARW',
 'DSC07891.ARW',
 'DSC07661.ARW',
 'DSC05710.ARW',
 'DSC06219.ARW',
 'DSC07107.ARW',
 'DSC07113.ARW',
 'DSC05704.ARW',
 'DSC07675.ARW',
 'DSC06580.ARW',
 'DSC07846.ARW',
 'DSC05937.ARW',
 'DSC05923.ARW',
 'DSC06594.ARW',
 'DSC07852.ARW',
 'DSC05909.ARW',
 'DSC07878.ARW',
 'DSC05935.ARW',
 'DSC07844.ARW',
 'DSC06582.ARW',
 'DSC07688.ARW',
 'DSC07850.ARW',
 'DSC06596.ARW',
 'DSC05921.ARW',
 'DSC07105.ARW',
 'DSC05712.ARW',
 'DSC07663.ARW',
 'DSC06569.ARW',
 'DSC07677.ARW',
 'DSC05706.ARW',
 'DSC07111.ARW',
 'DSC07139.ARW',
 'DSC06227.ARW',
 'DSC07887.ARW',
 'DSC06541.ARW',
 'DSC07893.ARW',
 'DSC06555.ARW',
 'DSC06233.ARW',
 'DSC06964.ARW',
 'DSC06970.ARW',
 'DSC06780.ARW',
 'DSC06958.ARW',
 'DSC06794.ARW',
 'DSC07461.ARW',
 'DSC05510.ARW',
 'DSC06019.ARW',
 'DSC07307.ARW',
 'DSC07313.ARW',
 'DSC05504.ARW',
 'DSC07475.ARW',
 'DSC06743.ARW',
 'DSC06025.ARW',
 'DSC05538.ARW',
 'DSC06031.ARW',
 'DSC07449.ARW',
 'DSC06757.ARW',
 'DSC06810.ARW',
 'DSC06804.ARW',
 'DSC06192.ARW',
 'DSC06186.ARW',
 'DSC07298.ARW',
 'DSC06838.ARW',
 'DSC07515.ARW',
 'DSC05464.ARW',
 'DSC07273.ARW',
 'DSC07267.ARW',
 'DSC06179.ARW',
 'DSC05470.ARW',
 'DSC07501.ARW',
 'DSC06637.ARW',
 'DSC07529.ARW',
 'DSC06151.ARW',
 'DSC05458.ARW',
 'DSC06145.ARW',
 'DSC06623.ARW',
 'DSC05869.ARW',
 'DSC06390.ARW',
 'DSC05699.ARW',
 'DSC05841.ARW',
 'DSC05855.ARW',
 'DSC06384.ARW',
 'DSC07071.ARW',
 'DSC05666.ARW',
 'DSC07717.ARW',
 'DSC06409.ARW',
 'DSC07703.ARW',
 'DSC05672.ARW',
 'DSC07065.ARW',
 'DSC05882.ARW',
 'DSC06353.ARW',
 'DSC06435.ARW',
 'DSC06421.ARW',
 'DSC06347.ARW',
 'DSC07059.ARW',
 'DSC05896.ARW',
 'DSC06420.ARW',
 'DSC05897.ARW',
 'DSC07058.ARW',
 'DSC06346.ARW',
 'DSC06352.ARW',
 'DSC05883.ARW',
 'DSC06434.ARW',
 'DSC07702.ARW',
 'DSC07064.ARW',
 'DSC05673.ARW',
 'DSC05667.ARW',
 'DSC07070.ARW',
 'DSC06408.ARW',
 'DSC07716.ARW',
 'DSC06385.ARW',
 'DSC05854.ARW',
 'DSC05840.ARW',
 'DSC05698.ARW',
 'DSC06391.ARW',
 'DSC05868.ARW',
 'DSC06144.ARW',
 'DSC06622.ARW',
 'DSC07528.ARW',
 'DSC06636.ARW',
 'DSC05459.ARW',
 'DSC06150.ARW',
 'DSC05471.ARW',
 'DSC06178.ARW',
 'DSC07266.ARW',
 'DSC07500.ARW',
 'DSC07514.ARW',
 'DSC07272.ARW',
 'DSC05465.ARW',
 'DSC07299.ARW',
 'DSC06187.ARW',
 'DSC06839.ARW',
 'DSC06193.ARW',
 'DSC06805.ARW',
 'DSC06811.ARW',
 'DSC06030.ARW',
 'DSC05539.ARW',
 'DSC06756.ARW',
 'DSC07448.ARW',
 'DSC06742.ARW',
 'DSC06024.ARW',
 'DSC05505.ARW',
 'DSC07312.ARW',
 'DSC07474.ARW',
 'DSC07460.ARW',
 'DSC07306.ARW',
 'DSC06018.ARW',
 'DSC05511.ARW',
 'DSC06795.ARW',
 'DSC06959.ARW',
 'DSC06781.ARW',
 'DSC06971.ARW',
 'DSC06965.ARW',
 'DSC06554.ARW',
 'DSC07892.ARW',
 'DSC06232.ARW',
 'DSC06226.ARW',
 'DSC07138.ARW',
 'DSC06540.ARW',
 'DSC07886.ARW',
 'DSC07676.ARW',
 'DSC06568.ARW',
 'DSC07110.ARW',
 'DSC05707.ARW',
 'DSC05713.ARW',
 'DSC07104.ARW',
 'DSC07662.ARW',
 'DSC06597.ARW',
 'DSC07851.ARW',
 'DSC07689.ARW',
 'DSC05920.ARW',
 'DSC05934.ARW',
 'DSC06583.ARW',
 'DSC07845.ARW',
 'DSC05908.ARW',
 'DSC07879.ARW',
 'DSC07699.ARW',
 'DSC06587.ARW',
 'DSC07841.ARW',
 'DSC05930.ARW',
 'DSC05924.ARW',
 'DSC06593.ARW',
 'DSC07855.ARW',
 'DSC05918.ARW',
 'DSC07869.ARW',
 'DSC06544.ARW',
 'DSC07882.ARW',
 'DSC06222.ARW',
 'DSC07128.ARW',
 'DSC06236.ARW',
 'DSC06550.ARW',
 'DSC07896.ARW',
 'DSC06578.ARW',
 'DSC07666.ARW',
 'DSC07100.ARW',
 'DSC05717.ARW',
 'DSC05703.ARW',
 'DSC07114.ARW',
 'DSC07672.ARW',
 'DSC06785.ARW',
 'DSC06791.ARW',
 'DSC06949.ARW',
 'DSC06961.ARW',
 'DSC06975.ARW',
 'DSC06020.ARW',
 'DSC05529.ARW',
 'DSC07458.ARW',
 'DSC06746.ARW',
 'DSC06752.ARW',
 'DSC06034.ARW',
 'DSC05515.ARW',
 'DSC07302.ARW',
 'DSC07464.ARW',
 'DSC07470.ARW',
 'DSC06008.ARW',
 'DSC07316.ARW',
 'DSC05501.ARW',
 'DSC06197.ARW',
 'DSC07289.ARW',
 'DSC06829.ARW',
 'DSC06183.ARW',
 'DSC06815.ARW',
 'DSC06801.ARW',
 'DSC06154.ARW',
 'DSC06632.ARW',
 'DSC06626.ARW',
 'DSC07538.ARW',
 'DSC05449.ARW',
 'DSC06140.ARW',
 'DSC05461.ARW',
 'DSC07276.ARW',
 'DSC06168.ARW',
 'DSC07510.ARW',
 'DSC07504.ARW',
 'DSC07262.ARW',
 'DSC05475.ARW',
 'DSC06395.ARW',
 'DSC05844.ARW',
 'DSC05688.ARW',
 'DSC05850.ARW',
 'DSC06381.ARW',
 'DSC05878.ARW',
 'DSC06430.ARW',
 'DSC05887.ARW',
 'DSC06356.ARW',
 'DSC07048.ARW',
 'DSC06342.ARW',
 'DSC05893.ARW',
 'DSC06424.ARW',
 'DSC07712.ARW',
 'DSC07074.ARW',
 'DSC05663.ARW',
 'DSC05677.ARW',
 'DSC07060.ARW',
 'DSC07706.ARW',
 'DSC06418.ARW',
 'DSC07061.ARW',
 'DSC05676.ARW',
 'DSC06419.ARW',
 'DSC07707.ARW',
 'DSC07713.ARW',
 'DSC05662.ARW',
 'DSC07075.ARW',
 'DSC05892.ARW',
 'DSC06343.ARW',
 'DSC06425.ARW',
 'DSC06431.ARW',
 'DSC07049.ARW',
 'DSC06357.ARW',
 'DSC05886.ARW',
 'DSC05879.ARW',
 'DSC06380.ARW',
 'DSC05851.ARW',
 'DSC05689.ARW',
 'DSC05845.ARW',
 'DSC06394.ARW',
 'DSC07505.ARW',
 'DSC05474.ARW',
 ...]